# -*- coding: utf-8 -*-
"""Basis01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N1wzAM-_at0mBvKxNUO5ISsWsRWCXiOi
"""

import numpy as np
import matplotlib.pyplot as plt

A=np.arange(1,13).reshape(3,4)
print(A)

B=np.random.randn(3,4)
print(B)

C=A.dot(B.T)
print(C)

print(C.shape)
print(C[:,0])

print(C.diagonal())

print(np.linalg.inv(C))

print(A*B)

print (B.mean())

print(B.sum())
###########Erstellen Sie eine Matrix D, die aus der 3, 1, 2 spalte
D=A[:,(3,1,2)]
print(D)

print(B.dot(A.T).shape)
print(A.dot(B.T))
print(A.dot(B.T).shape)

B=np.sqrt(A)
print(B)

B=B*B
print(B==A)

print(B.min())
B=np.random.randn(3,4)

ind = np.unravel_index(np.argmax(np.abs(B), axis=None), B.shape)
print(B)
print(ind)

print((A.flatten()[A.flatten()%2==1])[::-1])

A=np.vstack((A,[13,14,15,16]))
print(A)

v=b=np.ones((4,1))
print(A*v+b)

B=np.random.rand(4,4)
print(np.linalg.norm(A-B))
print(np.linspace(0,1,5))

def myGrid(a,b,n):
    x=np.linspace(a,b,n)
    xx,yy=np.meshgrid(x,x)
    return np.vstack((xx.flatten(),yy.flatten())).T

xy=myGrid(0,1,5)
plt.scatter(xy[:,0],xy[:,1])   
xy=myGrid(-1,1,3)
print(xy)

print(type(xy))
print (xy.dtype)

from timeit import default_timer as timer
start=timer()
myGrid(0,1,1000)
end=timer()
print(end-start)

from matplotlib.image import imread

n="https://7omcu3a78zp40klds2w28klr-wpengine.netdna-ssl.com/wp-content/uploads/2019/03/GettyImages-184621282.jpg"

im=imread(n)
im.shape

import os , sys
from google.colab import drive
drive.mount('/content/drive') #get access to drive

os.chdir("/content/drive/My Drive/PYP") # change working directory
print(os.getcwd())# read current work direktory


# we can use !ls ///// !cd !cp ......

os.mkdir("hi") # creat folder
!ls
with open('foo.txt', 'w') as f: # read and write files
    f.write('Hello Google Drive!')
f= open('foo.txt').read()
print(f)
import shutil## move everything!
shutil.move('/content/drive/My Drive/foo.txt','/content/drive/My Drive/PYP/foo.txt')

im=plt.imread("imgs/b.jpg")
im.shape
plt.imshow(im)

R,G,B=im[:,:,0],im[:,:,1],im[:,:,2]
import matplotlib.colors as colors
HSV=colors.rgb_to_hsv(im)
H=HSV[:,:,0]


plt.close()
plt.figure(1)
Bhist=plt.hist(B.flatten(),1000)
plt.figure(2)
Hhist=plt.hist(H.flatten(),1000)

